### ISSUE TITLE
Code from mrt is bugged

### ISSUE THREAD

**Issue by fjsj** [ayal/headly#2]
The code hosted at [Atmosphere](https://atmosphere.meteor.com/package/headly) is bugged.

I've did `mrt add headly` and the line 11 of downloaded code is:
`Meteor.headly._options = Meteor.headly._options;`
instead of
`Meteor.headly._options = options || Meteor.headly._options;`
which is the correct version.

**Comment by ayal** [comment]
@fjsj I'm so sorry this is embarrassing. I honestly don't know what was the exact problem with the publish process to Atmosphere since the master code was the correct way, i.e:

``` javascript
 Meteor.headly._options = options || Meteor.headly._options;
```

you can  try to remove and re-install the package or specifically version 0.0.42:

``` bash
mrt remove headly 
mrt add headly --version 0.0.42
```

or if this for some reason doesn't work (I've had Atmosphere insisting on installing v0.0.3 for about an hour) you can try changing the code yourself..

**Comment by fjsj** [comment]
No problem, I've bundled the master code in a lib directory of my project. 
Thanks for this great lib! I've just wanted to report the issue to you.
